# Generated by Django 4.0.6 on 2022-07-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0003_menulist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulist',
            name='menu',
            field=models.CharField(max_length=200),
        ),
    ]
