# Generated by Django 4.0.6 on 2022-07-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0005_alter_menulist_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_type', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='rslist',
            name='type',
            field=models.TextField(choices=[('veg', 'veg'), ('non-veg', 'non-veg')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='rslist',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rslist',
            name='cuisine',
            field=models.ManyToManyField(to='res.cuision'),
        ),
    ]
