# Generated by Django 4.0.6 on 2022-07-06 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0006_cuision_rslist_type_alter_rslist_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rslist',
            old_name='cuisine',
            new_name='cuision',
        ),
        migrations.AddField(
            model_name='menulist',
            name='cuision_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='cuision', to='res.cuision'),
        ),
    ]
