# Generated by Django 4.0.6 on 2022-07-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0007_rename_cuisine_rslist_cuision_menulist_cuision_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulist',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_item', to='res.rslist'),
        ),
    ]
