# Generated by Django 4.0.5 on 2022-07-06 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0009_alter_menulist_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulist',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='res.rslist'),
        ),
    ]
