# Generated by Django 4.0.5 on 2022-07-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0010_alter_menulist_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulist',
            name='name',
            field=models.ManyToManyField(to='res.rslist'),
        ),
    ]
