# Generated by Django 4.0.5 on 2022-07-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0011_menulist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulist',
            name='name',
        ),
    ]
