# Generated by Django 4.0.6 on 2022-07-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0012_remove_menulist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulist',
            name='ven',
            field=models.TextField(choices=[('veg', 'veg'), ('non-veg', 'non-veg')], default='1', max_length=10),
        ),
    ]
