# Generated by Django 4.0.6 on 2022-07-07 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0015_rslist_mulcui_alter_rslist_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rslist',
            name='mulcui',
        ),
    ]
