# Generated by Django 4.0.6 on 2022-07-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0016_remove_rslist_mulcui'),
    ]

    operations = [
        migrations.AddField(
            model_name='rslist',
            name='rating',
            field=models.FloatField(default=4.5),
            preserve_default=False,
        ),
    ]
