# Generated by Django 4.0.6 on 2022-07-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0017_rslist_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rslist',
            name='contact',
            field=models.CharField(default=1234567891, max_length=10),
            preserve_default=False,
        ),
    ]
